"""
Grid Convergence Index (GCI) Evaluator for Unstructured Meshes
Based on the methodology by Celik et al., 2008:
"Procedure for Estimation and Reporting of Uncertainty Due to Discretization in CFD Applications"

This tool calculates the apparent order of convergence and the GCI for 
simulations where the refinement ratio (r) is not perfectly uniform 
(e.g., meshes generated by snappyHexMesh).
"""

import numpy as np
import matplotlib.pyplot as plt

def evaluate_gci(N_cells, values, dimension=2):
    """
    Evaluates Grid Convergence Index (GCI), checks the asymptotic range, 
    and plots the results with Richardson Extrapolation.
    
    Parameters:
    N_cells   : list or array of exactly 3 cell counts [Fine, Medium, Coarse]
    values    : list or array of exactly 3 aerodynamic values [Fine, Medium, Coarse]
    dimension : 2 for 2D meshes (uses 1/sqrt(N)), 3 for 3D meshes (uses 1/N^(1/3))
    """
    print("======================================================")
    print("        UNSTRUCTURED GCI EVALUATOR (Celik et al.)     ")
    print("======================================================\n")

    # --- 0. Input Validation ---
    if len(N_cells) != 3 or len(values) != 3:
        raise ValueError("[ERROR] You must provide exactly 3 grid sizes and 3 corresponding values.")

    N = np.array(N_cells, dtype=float)
    phi = np.array(values, dtype=float)

    # --- 1. Calculate Characteristic Lengths (h) ---
    # Proportional to 1/N^(1/D)
    h = (1.0 / N) ** (1.0 / dimension)
    
    # --- 2. Calculate Refinement Ratios (r21, r32) ---
    r21 = h[1] / h[0]
    r32 = h[2] / h[1]
    
    if r21 <= 1.05 or r32 <= 1.05:
         print("[WARNING] Refinement ratio is very close to 1. Grids may not be sufficiently different.")

    print(f"Grid Sizes (N)       : Fine={N[0]:.0f}, Medium={N[1]:.0f}, Coarse={N[2]:.0f}")
    print(f"Values (phi)         : Fine={phi[0]:.5f}, Medium={phi[1]:.5f}, Coarse={phi[2]:.5f}")
    print(f"Refinement Ratio r21 : {r21:.4f}")
    print(f"Refinement Ratio r32 : {r32:.4f}\n")

    # --- 3. Calculate Differences ---
    eps21 = phi[1] - phi[0]
    eps32 = phi[2] - phi[1]
    
    # --- 4. Assess Convergence State ---
    # Prevent division by zero if coarse and medium are identical
    if abs(eps32) < 1e-12:
        print("[ERROR] Coarse and Medium grid values are identical. Cannot compute R.")
        return

    R = eps21 / eps32
    is_monotonic = (0 < R < 1)
    
    if is_monotonic:
        print("Convergence State    : [\u2713] Monotonic Convergence")
        
        # --- 5. Fixed-Point Iteration for Apparent Order of Convergence (p) ---
        # Required because r21 != r32 for unstructured meshes
        s = np.sign(eps32 / eps21)
        p = 1.0 # Initial guess
        
        for _ in range(1000): # Iteration loop
            try:
                q = np.log((r21**p - s) / (r32**p - s))
                p_new = abs(np.log(abs(eps32 / eps21)) + q) / np.log(r21)
                
                if abs(p_new - p) < 1e-6: # Convergence check
                    p = p_new
                    break
                p = p_new
            except ValueError:
                print("[WARNING] Math error in fixed-point iteration. Defaulting p=1.0")
                p = 1.0
                break
            
    elif -1 < R < 0:
        print("Convergence State    : [!] Oscillatory Convergence")
        print("Fallback applied     : Setting p = 1.0 due to oscillation.")
        p = 1.0
    else:
        print("Convergence State    : [X] Divergence")
        print("[ERROR] Cannot calculate reliable GCI for diverging grids.")
        return

    print(f"Order of Conv. (p)   : {p:.4f}")

    # --- 6. Richardson Extrapolation (Estimate value at h -> 0) ---
    phi_ext = phi[0] + (phi[0] - phi[1]) / (r21**p - 1.0)
    print(f"Richardson Extrap.   : {phi_ext:.5f}\n")

    # --- 7. Calculate GCI & Asymptotic Range ---
    Fs = 1.25 # Safety factor for 3 or more grids
    
    # Fine Grid GCI
    err21 = abs((phi[0] - phi[1]) / phi[0])
    gci_fine = (Fs * err21) / (r21**p - 1.0)
    
    # Coarse Grid GCI
    err32 = abs((phi[1] - phi[2]) / phi[1])
    gci_coarse = (Fs * err32) / (r32**p - 1.0)
    
    # Asymptotic Range Ratio (Should be approx 1.0)
    asymptotic_ratio = gci_coarse / ((r21**p) * gci_fine)
    
    print("======================================================")
    print("                   GCI RESULTS                        ")
    print("======================================================")
    print(f"Approx Relative Err  : {err21 * 100:.4f} %")
    print(f"GCI (Fine Grid)      : {gci_fine * 100:.4f} %")
    print(f"GCI (Coarse Grid)    : {gci_coarse * 100:.4f} %")
    print(f"Asymptotic Ratio     : {asymptotic_ratio:.4f} (Target: ~1.0)")
    print("======================================================\n")

    # ================= PLOTTING =================
    plt.figure(figsize=(8, 5))
    
    # X-axis is 1 / N^(1/D)
    x_vals = h
    x_extrap = 0.0 # h -> 0
    
    # Plot the 3 grid points
    plt.plot(x_vals, phi, marker='s', linestyle='-', color='tab:blue', label='CFD Results', markersize=8)
    
    # Plot the Richardson Extrapolation point
    plt.plot(x_extrap, phi_ext, marker='o', color='tab:orange', label='Richardson Extrap. ($h \\rightarrow 0$)', markersize=8)
    
    # Draw a dashed line connecting extrapolated point to the fine grid
    plt.plot([x_extrap, x_vals[0]], [phi_ext, phi[0]], linestyle='--', color='tab:orange')
    
    # Add GCI Error Bar to the fine grid point
    plt.errorbar(x_vals[0], phi[0], yerr=(gci_fine * phi[0]), color='black', capsize=5, label=f'GCI Uncertainty ($\\pm${gci_fine*100:.2f}%)')
    
    # Formatting
    plt.title('Grid Convergence Study (Celik et al.)', fontsize=14, pad=15)
    xlabel = r'$1 / \sqrt{N}$' if dimension == 2 else r'$1 / N^{1/3}$'
    plt.xlabel(xlabel + ' (Characteristic Grid Size)', fontsize=12)
    plt.ylabel('Aerodynamic Variable ($\\phi$)', fontsize=12)
    plt.grid(True, linestyle=':', alpha=0.7)
    plt.legend()
    
    # Reverse X-axis so it reads left-to-right from coarse to fine to extrapolated
    plt.xlim(max(x_vals) * 1.1, -0.05 * max(x_vals)) 
    
    plt.tight_layout()
    plt.show()

# ================= EXECUTION =================
if __name__ == "__main__":
    # --- Example Configuration ---
    # Ensure vectors are strictly ordered: [Fine, Medium, Coarse]
    
    # Example cell counts from snappyHexMesh
    cells_vector = [220000, 105000, 48000] 
    
    # Example extracted values (e.g., Cd, Cl, or Pressure Drop)
    values_vector = [0.3347, 0.3349, 0.3353]
    
    # Run the evaluator
    # Set dimension=2 for 2D airfoils, dimension=3 for full 3D models
    evaluate_gci(N_cells=cells_vector, values=values_vector, dimension=2)